env:
  browser: true
  es6: true
  node: true
extends:
  - 'eslint:recommended'
parser: 'babel-eslint'
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  quotes:
    - error
    - single
    - 'avoidEscape': true
  semi:
    - error
    - always
  no-console: 2
globals:
  'beforeEach': true
  'describe': true
  'it': true
  'before': true
  'after': true